# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award_app', '0002_auto_20190401_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default=5, max_length=30),
            preserve_default=False,
        ),
    ]
